### ISSUE TITLE
Release some documentation for InjectKeyboardInput/NtUserInjectKeyboardInput

### ISSUE THREAD

**Issue by JustBrandonLim** [AVISIX/Inputs.NET#2]
![image](https://github.com/AVISIX/Inputs.NET/assets/93673724/98f8562b-cd51-4134-b331-af2c51f487f8)

IDA does not have much information.

**Comment by AVISIX** [comment]
im not the one responsible for the documentation. as it says in the readme: its undocumented.

theres some resources online but ultimately it all is mostly similar to ntusersendinput. they all set the injected flags too and take mostly the same input arguments. 

pretty sure injectinput comes from the input injecton API which is being used in UWP.

also brandon, my dc acc got deleted, you can add me again. my handle is avisix
